//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITHRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int App_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<System.DateTime> apply_date { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
        public virtual user1 user { get; set; }
    }
}
