//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITHRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int id { get; set; }
        public string title { get; set; }
        public string major { get; set; }
        public string board { get; set; }
        public int year { get; set; }
        public Nullable<int> applicantid { get; set; }
    
        public virtual User User { get; set; }
        public virtual user1 user { get; set; }
    }
}
