//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITHRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ExperienceID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string Organization { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> CurrentlyWorking { get; set; }
    
        public virtual User User { get; set; }
        public virtual user1 user { get; set; }
    }
}
